[build]
  command = "quarto render"
  publish = "docs"

[build.environment]
  NODE_VERSION = "18"
  QUARTO_VERSION = "1.4.555"  # Remplace par la dernière version de Quarto

[context.production.environment]
  # Installer Quarto avant le build
  pre = """
    sudo apt-get update -y \\
    && sudo apt-get install -y wget \\
    && wget -qO- https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb -O quarto.deb \\
    && sudo dpkg -i quarto.deb \\
    && rm quarto.deb
  """
